# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'S.A.M' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for S.A.M
   pod 'Alamofire'
   pod 'AlamofireImage'
   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'CryptoSwift', '~> 1.3.4'

  target 'S.A.MTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'S.A.MUITests' do
    # Pods for testing
  end

end
